# Back-end Dockerfile

# Base Image
FROM node:20-alpine

# Install PM2 globally
RUN npm install -g pm2

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY src/server/package*.json ./

# Clean installation
RUN npm ci --only=production

# Copy application code
COPY . .

# Build the application
EXPOSE 3000

# Setting the enviornment
ENV NODE_ENV=production

# Start the app
CMD ["node", "server.js"]