# Docker Compose file the backend
version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - .backend/app
      - /app/node_modules
    environment:
      DB_HOST: DB_HOST
      DB_USER: DB_USER
      DB_PASSWORD: DB_PASSWORD
      DB_NAME: DB_NAME
      DB_PORT: DB_PORT
      PORT: 3000
      NODE_ENV: production
  
  frontend:
     build: ./frontend/opencourt
    

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: DB_NAME
    ports: 
      - "3307:3306"
