FROM node:lts-alpine AS builder

WORKDIR /app

COPY src/frontend/opencourt/package*.json ./

RUN npm install

COPY src/frontend/opencourt/ ./

RUN npm run build

FROM nginx:1.25-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80